"""
Django settings for student project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from django.utils.translation import ugettext_lazy as _
import os
import dotenv

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jc4@!6#ya+ek5jh!knnn!x1-m51l&d==57e74(kldl-$!380fk'
DEBUG = True
PRODUCTION = False

##-- Production settings
if os.environ.get("PRODUCTION", False):
    DEBUG = False
    PRODUCTION = True
if "DEBUG" in os.environ:
    DEBUG = os.environ['DEBUG']
if "SECRET_KEY" in os.environ:
    SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    ##-- Admin
    'djangocms_admin_style',
    ##-- Custom apps
    'main.apps.MainConfig',
    'users.apps.UsersConfig',
    ##-- Built-in
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ##-- CMS + Third-party
    # 'django_filters',
    'sekizai',
    'django.contrib.sites',
    'cms',
    'menus',
    'filer',
    'easy_thumbnails',
    'mptt',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_snippet',
    'djangocms_text_ckeditor',
    'treebeard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    #-- For CMS
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'cms.middleware.utils.ApphookReloadMiddleware',
]

CSRF_TRUSTED_ORIGINS = ['*', "easyschool.1001cyprus.com"]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDINTIALS = True
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'student.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai', # For CMS
                'cms.context_processors.cms_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'student.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
if PRODUCTION:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
    DATABASES = {
        "default": {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ.get("PG_TABLE", '1001cyprus'),
            "USER": os.environ.get("PG_USER", "postgres"),
            "PASSWORD": os.environ.get("PG_PASSWORD", "12345"),
            "HOST": os.environ.get("PG_HOST", "localhost"),
            "PORT": os.environ.get("PG_PORT", "5432"),
        }
    }
    CONN_MAX_AGE = 60

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'
AUTHENTICATION_BACKENDS = ('users.backends.EmailAuthBackend',)

INTERNAL_IPS = [
    '127.0.0.1',
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru'

LANGUAGES = [
    ('ru', 'Русский'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Etc/GMT-2'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SITE_ID = int(os.environ.get('SITE_ID', "1"))

THUMBNAIL_HIGH_RESOLUTION = True

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

CMS_TEMPLATES = (
    ('cms_base.html', 'Base'),
)

DJANGOCMS_SNIPPET_SEARCH = True
DJANGOCMS_SNIPPET_CACHE = False # default value is True

DJANGOCMS_SNIPPET_THEME = 'github'
DJANGOCMS_SNIPPET_MODE = 'html'

CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
    'toolbar': 'CMS',
    'skin': 'moono-lisa',
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 50*1024*1024 #30MB

CMS_PLACEHOLDER_CONF = {
    'top_menu': {
        'name': _('Верхнее меню'),
        'plugins': ['TopMenuPlugin'],
        'default_plugins': [
            {
                'plugin_type': 'TopMenuPlugin',
                'values': {},
                'children': [
                    {
                        'plugin_type': 'LinkPlugin',
                        'values': {
                            'name': 'Как это работает',
                            'external_link': '/faq#how-works'
                        }
                    },
                    {
                        'plugin_type': 'LinkPlugin',
                        'values': {
                            'name': 'Заказать работу',
                            'external_link': '#order-work'
                        }
                    },
                ]
            }
        ]
    },
    'footer_links': {
        'name': _('Ссылки футера'),
        'plugins': ['LinkPlugin'],
        'default_plugins': [
            {
                'plugin_type': 'LinkPlugin',
                'values': {
                    'name': 'Условия использования',
                    'external_link': '/use-terms'
                }
            },
            {
                'plugin_type': 'LinkPlugin',
                'values': {
                    'name': 'FAQ',
                    'external_link': '/faq'
                }
            },
            {
                'plugin_type': 'LinkPlugin',
                'values': {
                    'name': 'Поддержка',
                    'external_link': '#support'
                }
            },
            {
                'plugin_type': 'LinkPlugin',
                'values': {
                    'name': 'Для правообладателей',
                    'external_link': '/for-copyright-holders'
                }
            },
            {
                'plugin_type': 'LinkPlugin',
                'values': {
                    'name': 'Карта сайта',
                    'external_link': '/sitemap'
                }
            },
            {
                'plugin_type': 'LinkPlugin',
                'values': {
                    'name': 'Заказать работу',
                    'external_link': '#order-work'
                }
            },
        ]
    },
    'footer_text':{
        'name': _('Текст футера'),
        'plugins': ['TextPlugin', 'LinkPlugin'],
        'default_plugins': [
            {
                'plugin_type': 'TextPlugin',
                'values': {
                    'body': 'Copyright &copy; 2021'
                }
            }
        ]
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static_all'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if not DEBUG or PRODUCTION or "EMAIL_HOST" in os.environ:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    # EMAIL_SERVER = os.environ.get("EMAIL_SERVER")
    EMAIL_HOST = os.environ.get("EMAIL_HOST")
    EMAIL_PORT = os.environ.get("EMAIL_PORT")
    EMAIL_USE_TLS = os.environ.get("EMAIL_TLS", False)
    EMAIL_USE_SSL = os.environ.get("EMAIL_SSL", False)
    EMAIL_HOST_USER = os.environ.get("EMAIL_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_PASSWORD")
    ##
    SERVER_EMAIL = EMAIL_HOST_USER
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
    EMAIL_SUBJECT_PREFIX = '[1001Cyprus] ' if PRODUCTION and not DEBUG else '[1001Cyprus (Debug)] '

ADMINS = [
        ('Programmer and site administrator', 'djpy@1001cyprus.com'),
    ]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        # Include the default Django email handler for errors
        # This is what you'd get without configuring logging at all.
        'mail_admins': {
            'class': 'django.utils.log.AdminEmailHandler',
            'level': 'ERROR',
             # But the emails are plain text by default - HTML is nicer
            'include_html': True,
        },
        # Log to a text file that can be rotated by logrotate
        'logfile': {
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': 1024,  # 3 MB
            'level': 'DEBUG',
            'filename': os.path.join(BASE_DIR, 'django.log'),
            # 'maxBytes': '1024*5', #5kb
            # 'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        }
    },
    'loggers': {
        # Again, default Django configuration to email unhandled exceptions
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        # Might as well log any errors anywhere else in Django
        'django': {
            'handlers': ['logfile', 'console'],
            'level': 'INFO' if DEBUG else 'ERROR',
            'propagate': False,
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'datefmt' : "%d/%b/%Y %H:%M:%S",
            'style':'{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    }
}
